app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', ['uses' => 'ScreenController@index', 'as' => 'screen.dashboard']);
Route::get('/error', ['uses' => 'ScreenController@error', 'as' => 'screen.error']);

Route::group(['middleware' => 'guest', 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('login', ['as' => 'login', 'uses' => 'UserController@login']);
    Route::post('login', ['as' => 'authenticate', 'uses' => 'UserController@authenticate']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'UserController@logout']);
});

Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'UserController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'UserController@create']);
        Route::post('', ['as' => 'store', 'uses' => 'UserController@store']);
        Route::get('{id}/show', ['as' => 'show', 'uses' => 'UserController@show']);
        Route::get('{id}/edit', ['as' => 'edit', 'uses' => 'UserController@edit']);
        Route::post('{id}', ['as' => 'update', 'uses' => 'UserController@update']);
        Route::get('logout', ['as' => 'logout', 'uses' => 'UserController@logout']);
        Route::get('profile', ['as' => 'editMyProfile', 'uses' => 'UserController@editMyProfile']);
        Route::post('profile', ['as' => 'updateMyProfile', 'uses' => 'UserController@updateMyProfile']);
        Route::get('password', ['as' => 'editPassword', 'uses' => 'UserController@editPassword']);
        Route::post('password', ['as' => 'updatePassword', 'uses' => 'UserController@updatePassword']);
    });
    Route::group(['prefix' => 'project', 'as' => 'project.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'ProjectController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'ProjectController@create']);
        Route::get('{id}/edit', ['as' => 'edit', 'uses' => 'ProjectController@edit']);
        Route::get('{id}/show', ['as' => 'show', 'uses' => 'ProjectController@show']);
        Route::put('{id}', ['as' => 'update', 'uses' => 'ProjectController@update']);
        Route::post('', ['as' => 'store', 'uses' => 'ProjectController@store']);
        Route::group(['prefix' => '{id}/raid', 'as' => 'raid.'], function () {
            Route::get('create/{type}', ['as' => 'create', 'uses' => 'RaidController@create']);
            Route::get('edit/{raid}', ['as' => 'edit', 'uses' => 'RaidController@edit']);
            Route::get('rag/{raid}/{rag}', ['as' => 'rag', 'uses' => 'RaidController@rag']);
            Route::get('priority/{raid}/{priority}', ['as' => 'priority', 'uses' => 'RaidController@priority']);
            Route::post('', ['as' => 'store', 'uses' => 'RaidController@store']);
            Route::put('{raid}', ['as' => 'update', 'uses' => 'RaidController@update']);
            Route::delete('{raid}', ['as' => 'destroy', 'uses' => 'RaidController@destroy']);
        });
        Route::group(['prefix' => '{id}/delay', 'as' => 'delay.'], function () {
            Route::get('create', ['as' => 'create', 'uses' => 'Project\DelayController@create']);
            Route::post('', ['as' => 'store', 'uses' => 'Project\DelayController@store']);
        });
    });
});

Route::controller('/sample', 'SampleController');

app/Models/User.php
<?php

namespace App\Models;

use App\User as BaseUser;
use Carbon\Carbon;


class User extends BaseUser
{
    const USER_ROLE_SUPERUSER = 'super';
    const USER_ROLE_ADMINISTRATOR = 'admin';
    const USER_ROLE_CSM = 'csm';
    const USER_ROLE_PM = 'pm';

    public function getStatusAttribute()
    {
        if (isset($this->attributes['deleted_at'])) {
            return (empty($this->attributes['deleted_at'])) ? 'active' : 'suspended';
        }
        return 'active';
    }

    public function setStatusAttribute($value)
    {
        if('suspended' == $value){

            $this->attributes['deleted_at'] = self::now();
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use App\Models\Base as Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\UserRepository;
use Illuminate\Foundation\Auth\ThrottlesLogins;
use Illuminate\Http\Request;
use App\Http\Requests;
use Auth;
use Gate;
use Validator;
use Illuminate\Support\Facades\Hash;
use App\Http\Requests\User\LoginRequest;
use App\Http\Requests\User\UpdateMyProfileRequest;
use App\Http\Requests\User\UpdatePasswordRequest;
use App\Http\Requests\User\CreateProfileRequest;
use App\Http\Requests\User\UpdateProfileRequest;

class UserController extends Controller
{
//    use AuthenticatesAndRegistersUsers, ThrottlesLogins;
    use ThrottlesLogins;


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $repo = new UserRepository();
        $model = $repo->model();
        $users = $model->where('role', '!=', 'super')->orderBy('name', 'ASC')->get();
        return view('pages.user.index', [
            'users' => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Gate::denies('manage-users')) {
            return redirect()->route('screen.error');
        }
        $repo = new UserRepository();
        $user = $repo->model();
        return view('pages.user.form', [
            'user' => $user,
            'action' => route('user.store'),
            'superuser' => false
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateProfileRequest $request)
    {
        $repo = new UserRepository();
        $user = $repo->model();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->role = $request->role;
        $user->password = Hash::make('1234');
        $user->save();
        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Gate::denies('manage-users')) {
            return redirect()->route('screen.error');
        }

        try {
            $user = UserRepository::findOrFail($id);
        } catch (\Exception $e) {
            return redirect()->route('screen.error');
        }

        return view('pages.user.form', [
            'user' => $user,
            'action' => route('user.update', ['id' => $user->id]),
            'superuser' => true
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProfileRequest $request, $id)
    {
        if (Gate::denies('manage-users')) {
            return redirect()->route('screen.error');
        }

        try {
            $user = UserRepository::findOrFail($id);
        } catch (\Exception $e) {
            return redirect()->route('screen.error');
        }
        $user->name = $request->name;
        $user->email = $request->email;
        $user->role = $request->role;
        $user->save();
        if ('suspended' == $request->status) {
            $user->delete();
        }
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function login()
    {
        return view('pages.user.login');
    }


    public function authenticate(LoginRequest $request)
    {

        if ($this->hasTooManyLoginAttempts($request)) {
            return $this->sendLockoutResponse($request);
        }


        if (Auth::attempt($request->only('email', 'password'), $request->has('remember'))) {
            $this->clearLoginAttempts($request);
            return redirect()->route('screen.dashboard');
        }

        // If the login attempt was unsuccessful we will increment the number of attempts
        // to login and redirect the user back to the login form. Of course, when this
        // user surpasses their maximum number of attempts they will get locked out.
        $this->incrementLoginAttempts($request);


        return redirect()->route('user.login')
            ->withInput($request->only('email', 'remember'))
            ->withErrors([
                'email' => 'Wrong email or password',
            ]);
    }

    public function logout()
    {
        Auth::logout();
        return redirect()->route('user.login');
    }

    protected function loginUsername()
    {
        return 'email';
    }

    public function editMyProfile()
    {
        $user = UserRepository::myProfile();
        return view('pages.user.form', [
            'user' => $user,
            'action' => route('user.editMyProfile'),
            'superuser' => false
        ]);
    }

    public function updateMyProfile(UpdateMyProfileRequest $request)
    {
        $profile = UserRepository::myProfile()->model();
        $profile->name = $request->name;
        $profile->email = $request->email;
        $profile->save();
        return redirect()->route('screen.dashboard');
    }

    public function editPassword()
    {
        return view('pages.user.form.password');
    }

    public function updatePassword(UpdatePasswordRequest $request)
    {

        $profile = UserRepository::myProfile()->model();
        $profile->password = Hash::make($request->password);
        $profile->save();
        return redirect()->route('screen.dashboard');
    }
}

resources/views/pages/user/form.blade.php
@extends('layout')
@section('title','Update profile')
@section('id','manage-users')
@section('class','manage-users')

@section('content')
        <!-- /.row -->
<div class="row">
    <div class="col-lg-6 col-lg-offset-3">
        <form name="user" method="post" action="{{$action}}">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-12">
                            <h5 class="pull-left"><i
                                        class="fa fa-fw fa-user"> </i> {{(null != $user->id)? 'Edit user': 'Create new user'}}
                            </h5>
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="row">


                        {{csrf_field()}}

                        <div class="form-group">
                            <div class="col-md-6">
                                <!-- Mspp Code element-->
                                {!! formElementText('name', 'Name: ', $user->name, [
                                    'tooltip'=>'Your name',
                                    'placeholder'=>'Name'
                                ], $errors) !!}
                                        <!-- ./Mspp Code-->

                            </div>
                            <div class="col-md-6">
                                <!-- Mspp Code element-->
                                {!! formElementText('email', 'Email: ', $user->email, [
                                    'tooltip'=>'Your email',
                                    'placeholder'=>'Email'
                                ], $errors) !!}
                                        <!-- ./Mspp Code-->

                            </div>
                            @can('manage-users')
                            <div class="col-md-6">
                                <!-- Mspp Code element-->
                                {!! formElementSelect('role', 'Role: ', $user->role,roles(), [
                                    'tooltip'=>'User role'
                                ], $errors) !!}
                                        <!-- ./Mspp Code-->

                            </div>
                            <div class="col-md-6">
                                <!-- Mspp Code element-->
                                {!! formElementSelect('status', 'Status: ', $user->status, [
                                    'active'=>'Active',
                                    'suspended'=>'Suspended'
                                ], [
                                    'tooltip'=>'Status'
                                ], $errors) !!}
                                        <!-- ./Mspp Code-->

                            </div>
                            @endcan
                        </div>


                    </div>

                </div>
                <!-- /.panel-body -->
                <div class="panel-footer">
                    <div class="row">
                        @include('pages.partials.form.create', [
                            'return'=>route('user.index')
                        ])
                    </div>
                </div>
            </div>
        </form>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
@stop

resources/views/pages/user/index.blade.php
@extends('layout')
@section('title','Manage users')
@section('id','manage-users')
@section('class','manage-users')

@section('content')
        <!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-12">
                        <h5 class="pull-left"><i class="fa fa-fw fa-file"> </i> List of users</h5>

                        <div class="btn-group btn-group-sm text-right pull-right dropdown">
                            <a class="btn btn-default" href="{{route('user.create')}}">
                                <i class="fa fa fa-plus-square"> </i> Add</a>

                            <a role="button" data-toggle="dropdown" class="btn btn-primary dt-cc"
                               data-table-rel="#user-index-table">
                                <i class="fa fa-columns"> </i> Columns <span class="caret"></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover datatable" data-length="25"
                           id="user-index-table" style="display: none">
                        <thead>
                        <tr>
                            <th>Order</th>
                            <th>ID</th>
                            <th data-class="expand">Name</th>
                            <th>Email</th>
                            <th data-hide="phone">Role</th>
                        </tr>
                        </thead>

                        <tbody>
                        <?php $i = 0;?>
                        @foreach($users as $user)
                            <tr class="row-red odd" role="row">
                                <td>{{++$i}}</td>
                                <td><a href="{{route('user.edit', ['id'=>$user->id])}}">{{$user->id}}</a></td>
                                <td><a href="{{route('user.edit', ['id'=>$user->id])}}">{{$user->name}}</a></td>
                                <td>{{$user->email}}</td>
                                <td>{{trans('component.role.'.$user->role)}}</td>

                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
@stop

resources/views/pages/user/login.blade.php
@extends('blank')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">Login</div>
                    <div class="panel-body">
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <form role="form" method="POST"
                              action="{{ route('user.authenticate') }}">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">

                            <div class="form-group">
                                <input type="email" placeholder="Email" class="form-control" name="email"
                                       value="{{ old('email') }}">
                            </div>

                            <div class="form-group">
                                <input type="password" placeholder="Password" class="form-control" name="password">
                            </div>

                            <div class="form-group">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="remember"> Remember Me
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-lg btn-success btn-block">Login</button>
                                <a class="btn btn-link" href="{{ url('/password/email') }}">Forgot Your
                                    Password?</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection