app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', ['uses' => 'ScreenController@index', 'as' => 'screen.dashboard']);
Route::get('/error', ['uses' => 'ScreenController@error', 'as' => 'screen.error']);

Route::group(['middleware' => 'guest', 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('login', ['as' => 'login', 'uses' => 'UserController@login']);
    Route::post('login', ['as' => 'authenticate', 'uses' => 'UserController@authenticate']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'UserController@logout']);
});

Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'UserController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'UserController@create']);
        Route::post('', ['as' => 'store', 'uses' => 'UserController@store']);
        Route::get('{id}/show', ['as' => 'show', 'uses' => 'UserController@show']);
        Route::get('{id}/edit', ['as' => 'edit', 'uses' => 'UserController@edit']);
        Route::post('{id}', ['as' => 'update', 'uses' => 'UserController@update']);
        Route::get('logout', ['as' => 'logout', 'uses' => 'UserController@logout']);
        Route::get('profile', ['as' => 'editMyProfile', 'uses' => 'UserController@editMyProfile']);
        Route::post('profile', ['as' => 'updateMyProfile', 'uses' => 'UserController@updateMyProfile']);
        Route::get('password', ['as' => 'editPassword', 'uses' => 'UserController@editPassword']);
        Route::post('password', ['as' => 'updatePassword', 'uses' => 'UserController@updatePassword']);
    });
    Route::group(['prefix' => 'project', 'as' => 'project.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'ProjectController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'ProjectController@create']);
        Route::get('{id}/edit', ['as' => 'edit', 'uses' => 'ProjectController@edit']);
        Route::get('{id}/show', ['as' => 'show', 'uses' => 'ProjectController@show']);
        Route::put('{id}', ['as' => 'update', 'uses' => 'ProjectController@update']);
        Route::post('', ['as' => 'store', 'uses' => 'ProjectController@store']);
        Route::group(['prefix' => '{id}/raid', 'as' => 'raid.'], function () {
            Route::get('create/{type}', ['as' => 'create', 'uses' => 'RaidController@create']);
            Route::get('edit/{raid}', ['as' => 'edit', 'uses' => 'RaidController@edit']);
            Route::get('rag/{raid}/{rag}', ['as' => 'rag', 'uses' => 'RaidController@rag']);
            Route::get('priority/{raid}/{priority}', ['as' => 'priority', 'uses' => 'RaidController@priority']);
            Route::post('', ['as' => 'store', 'uses' => 'RaidController@store']);
            Route::put('{raid}', ['as' => 'update', 'uses' => 'RaidController@update']);
            Route::delete('{raid}', ['as' => 'destroy', 'uses' => 'RaidController@destroy']);
        });
        Route::group(['prefix' => '{id}/delay', 'as' => 'delay.'], function () {
            Route::get('create', ['as' => 'create', 'uses' => 'Project\DelayController@create']);
            Route::post('', ['as' => 'store', 'uses' => 'Project\DelayController@store']);
        });
    });
});

Route::controller('/sample', 'SampleController');

app/Models/Project.php
<?php
/**
 * Created by PhpStorm.
 * User: madam
 * Date: 10/14/2015
 * Time: 5:41 PM
 */

namespace App\Models;

use App\Models\Project\Delay;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Project extends Base
{
    use SoftDeletes;
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'projects';


    public function customer()
    {
        return $this->belongsTo(Customers::class);
    }

    public function pm()
    {
        return $this->belongsTo(User::class);
    }

    public function csm()
    {
        return $this->belongsTo(User::class);
    }

    public function delays()
    {
        $relation = $this->hasMany(Delay::class);
        return $relation->orderBy('created_at', 'DESC')->orderBy('id', 'DESC');
    }

    public function getModifiedEndDateAttribute()
    {
        $estimation = new Carbon($this->attributes['estimated_at']);
        return $estimation->addWeekdays($this->delays->sum('days'))->format(self::DATE_MASK);
    }


    public function risks()
    {
        $relation = $this->hasMany(Raid::class);
        return $relation->where('type', 'risk');
    }

    public function actions()
    {
        $relation = $this->hasMany(Raid::class);
        return $relation->where('type', 'action');
    }

    public function issues()
    {
        $relation = $this->hasMany(Raid::class);
        return $relation->where('type', 'issue');
    }

    public function dependencies()
    {
        $relation = $this->hasMany(Raid::class);
        return $relation->where('type', 'dependency');
    }


}

app/Models/Project/Delay.php
<?php

namespace App\Models\Project;

use App\Models\Project;
use App\Models\Base;
use Carbon\Carbon;

class Delay extends Base
{
    protected $table = 'project_delay';

    public function project()
    {
        return $this->belongsTo(Project::class);
    }

   
}

app/Http/Controllers/Api/V1/ProjectController.php
<?php

namespace App\Http\Controllers\Api\V1;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Project;
use Response;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = ["type_id" => "2",
            "phase_id" => "2",
            "customer_id" => "5",
            "pm_id" => "muhammet.alay@monitise.com",
            "rank_id" => "2",
            "name" => "sss",
            "code" => "ssss",
            "complete" => "0",
            "reason" => "sss",
            "started_at" => "14/10/2015",
            "estimated_at" => "23/10/2015",
            "finished_at" => "30/10/2015",
            "updated_at" => "2015-10-14 15:16:48",
            "created_at" => "2015-10-14 15:16:48"];
        $project = new Project();
        try {
            $project->insert($request->all());
            return Response::json($project);
        } catch (\Exception $e) {
            return Response::json([
                'error' => $e->getMessage(),
                'project' => $project
            ]);
        }


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $project = new Project();

        $project->type_id = $request->get('type_id');
        $project->phase_id = $request->get('phase_id');
        $project->customer_id = $request->get('customer_id');
        $project->pm_id = $request->get('pm_id');
        $project->rank_id = $request->get('rank_id');
        $project->name = $request->get('name');
        $project->code = $request->get('code');
        $project->complete = $request->get('complete');
        $project->reason = $request->get('reason');
        $project->started_at = $request->get('started_at');
        $project->estimated_at = $request->get('estimated_at');
        $project->finished_at = $request->get('finished_at');
//        dd($project);
        try {
            $project->save();
            return Response::json($project);
        } catch (\Exception $e) {
            return Response::json([
                'error' => $e->getMessage(),
                'project' => $project
            ]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Api/V2/ProjectController.php
<?php

namespace App\Http\Controllers\Api\V2;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Response;
use Ps\Repository as Ps;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $ps = new Ps();
        $ps->login();

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Project/DelayController.php
<?php

namespace App\Http\Controllers\Project;

use App\Models\Project;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Project\Delay;
use App\Http\Requests\Project\CreateDelayRequest;

class DelayController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($projecyId)
    {
        $delay = new Delay();
        $delay->project_id = $projecyId;
        $delay->dependency = old('dependency');
        $delay->category = old('category');
        $delay->reason = old('phase');
        $delay->days = old('days');

        return view('pages.project.delay.form', [
            'delay' => $delay,
            'form' => [
                'url' => route('project.delay.store', ['id' => $projecyId]),
                'method' => 'post',
                'name' => 'Delay project'
            ]
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store($projectId, CreateDelayRequest $request)
    {
        $delay = new Delay();
        $delay->project_id = $projectId;
        $delay->days = $request->days;
        $delay->dependency = $request->dependency;
        $delay->category = $request->category;
        $delay->reason = $request->reason;
        try {
            $delay->save();
            $delay->project->touch();
            return redirect()->route('project.show', [$projectId]);
        } catch (\Exception $e) {
            return redirect()->route('screen.error')->withErrors(['errors' => $e->getMessage()]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/project/partials/actions.blade.php
@if(!$elements->isEmpty())
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default" id="actions-panel-report">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-12">
                            <h5 class="pull-left"><i class="fa fa-fw fa-file"> </i> {{trans('component.raid.action')}}
                            </h5>

                            <div class="btn-group btn-group-sm text-right pull-right padding-7">
                                <a class="btn btn-default" href="{{route('project.raid.create', [
                                    'id'=>$project_id,
                                    'type'=>'action'
                                ])}}">
                                    <i class="fa fa fa-plus-square"> </i> Add</a>
                                <a role="button" data-toggle="dropdown" class="btn  btn-xs btn-primary dt-cc"
                                   data-table-rel="#raid-action-table">
                                    <i class="fa fa-columns"> </i> Columns <span class="caret"></span>
                                </a>

                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover datatable"
                               id="raid-action-table"
                               style="display: none" data-length="10">
                            <thead>
                            <tr>
                                <th>No.</th>
                                <th>Description</th>
                                <th>Date raised</th>
                                <th>Agreed completion date</th>
                                <th>Responsible</th>
                                <th>Update</th>
                                <th>Priority L/M/H</th>
                                <th>Status</th>
                                <th></th>
                            </tr>
                            </thead>

                            <tbody>
                            <?php $i = 0; ?>
                            @foreach($elements as $e)
                                <tr class="{{$e->class}}">
                                    <td>
                                        {{++$i}}
                                    </td>
                                    <td>{{$e->description}}</td>
                                    <td>{{$e->created_at}}</td>
                                    <td>{{$e->estimated_at}}</td>
                                    <td>
                                        {{(null != $e->owner) ? $e->owner->name : ''}}
                                    </td>
                                    <td>{{$e->mitigation}}</td>
                                    <td>{{trans('component.lmh.'.$e->priority)}}</td>
                                    <td>{{(null != $e->deleted_at)? 'Closed': 'Active'}}</td>
                                    <td class="text-right">
                                        @if(null == $e->deleted_at)
                                        <!-- Single button -->
                                        <div class="btn-group btn-group-xs dropup">
                                            <button type="button" class="btn btn-{{$e->class}} dropdown-toggle"
                                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fa fa-cogs"> </i> <span class="caret"> </span>
                                            </button>
                                            <ul class="dropdown-menu  dropdown-menu-right">
                                                <li><a href="{{route('project.raid.edit',[
                                                    'id'=>$project_id,
                                                    'raid'=>$e->id
                                               ])}}"><i class="fa fa-pencil"> </i> Edit</a></li>
                                                <li role="separator" class="divider"></li>
                                                <li><a class="action-confirm" data-confirm="#change-rag-modal" href="{{route('project.raid.priority',[
                                                    'id'=>$project_id,
                                                    'raid'=>$e->id,
                                                    'priority'=>'high'
                                               ])}}"><i class="fa  fa-circle text-danger"> </i> High</a></li>
                                                <li><a class="action-confirm" data-confirm="#change-rag-modal" href="{{route('project.raid.priority',[
                                                    'id'=>$project_id,
                                                    'raid'=>$e->id,
                                                    'priority'=>'medium'
                                               ])}}"><i class="fa  fa-circle text-warning"> </i> Medium</a></li>
                                                <li><a class="action-confirm" data-confirm="#change-rag-modal" href="{{route('project.raid.priority',[
                                                    'id'=>$project_id,
                                                    'raid'=>$e->id,
                                                    'priority'=>'low'
                                               ])}}"><i class="fa  fa-circle text-success"> </i> Low</a></li>
                                                @if(!$e->deleted_at != null)
                                                    <li role="separator" class="divider"></li>

                                                    <li><a class="form-confirm" data-confirm="#close-modal" href="{{route('project.raid.destroy',[
                                                    'id'=>$project_id,
                                                    'raid'=>$e->id
                                                    ])}}"> <i class="fa  fa-check"> </i> Close</a>
                                                    </li>
                                                @endif
                                            </ul>
                                        </div>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endif

resources/views/pages/project/partials/dependencies.blade.php
@include('pages.project.partials.risks', [
                'elements'=>$elements,
                'type'=>$type,
                'project_id'=>$project_id
])

resources/views/pages/project/partials/issues.blade.php
@include('pages.project.partials.risks', [
                'elements'=>$elements,
                'type'=>$type,
                'project_id'=>$project_id
])

resources/views/pages/project/partials/risks.blade.php
<!-- /.row -->
@if(!$elements->isEmpty())
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default" id="{{$container}}">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-12">
                            <h5 class="pull-left"><i class="fa fa-fw fa-file"> </i> {{trans('component.raid.'.$type)}}
                            </h5>

                            <div class="btn-group btn-group-sm text-right pull-right padding-7">
                                <a class="btn btn-default" href="{{route('project.raid.create', [
                                    'id'=>$project_id,
                                    'type'=>$type
                                ])}}">
                                    <i class="fa fa fa-plus-square"> </i> Add</a>
                                <a role="button" data-toggle="dropdown" class="btn  btn-xs btn-primary dt-cc"
                                   data-table-rel="#raid-{{$type}}-table">
                                    <i class="fa fa-columns"> </i> Columns <span class="caret"></span>
                                </a>

                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover datatable"
                               id="raid-{{$type}}-table"
                               style="display: none" data-length="10">
                            <thead>
                            <tr>
                                <th>Order</th>
                                <th data-class="expand">Description (What might happen)</th>
                                <th>Impact (What would this impact)</th>
                                <th data-hide="phone">Date raised</th>
                                <th data-hide="phone">Risk Author</th>
                                <th data-hide="phone,tablet">Risk Owner</th>
                                <th data-hide="phone,tablet">Mitigation Actions</th>
                                <th data-hide="phone,tablet">Probability</th>
                                <th data-hide="phone,tablet">Impact</th>
                                <th data-hide="phone,tablet">RAG Status</th>
                                <th data-hide="phone,tablet" data-status="All">Status</th>
                                <th></th>
                            </tr>
                            </thead>

                            <tbody>
                            <?php $i = 0; ?>
                            @foreach($elements as $e)
                                <tr class="{{$e->class}}">
                                    <td>
                                        {{++$i}}
                                    </td>
                                    <td>{{$e->description}}</td>
                                    <td>{{$e->impact->description}}</td>
                                    <td>{{$e->impact->raised_at}}</td>
                                    <td>
                                        {{(null != $e->author) ? $e->author->name : ''}}
                                    </td>
                                    <td>
                                        {{(null != $e->owner) ? $e->owner->name : ''}}
                                    </td>
                                    <td>{{$e->mitigation}}</td>
                                    <td>{{trans('component.lmh.'.$e->probability)}}</td>
                                    <td>{{trans('component.lmh.'.$e->impact->level)}}</td>
                                    <td>{{trans('component.color.'.$e->rag)}}</td>
                                    <td>{{(null != $e->deleted_at)? 'Closed': 'Active'}}</td>
                                    <td class="text-right">
                                        <!-- Single button -->
                                        @if(null == $e->deleted_at)
                                            <div class="btn-group btn-group-xs dropup">
                                                <button type="button" class="btn btn-{{$e->class}} dropdown-toggle"
                                                        data-toggle="dropdown" aria-haspopup="true"
                                                        aria-expanded="false">
                                                    <i class="fa fa-cogs"> </i> <span class="caret"> </span>
                                                </button>
                                                <ul class="dropdown-menu  dropdown-menu-right">
                                                    <li><a href="{{route('project.raid.edit',[
                                                    'id'=>$project_id,
                                                    'raid'=>$e->id
                                               ])}}"><i class="fa fa-pencil"> </i> Edit</a></li>
                                                    <li role="separator" class="divider"></li>
                                                    <li><a class="action-confirm" data-confirm="#change-rag-modal"
                                                           href="{{route('project.raid.rag',[
                                                    'id'=>$project_id,
                                                    'raid'=>$e->id,
                                                    'rag'=>'red'
                                               ])}}"><i class="fa  fa-circle text-danger"> </i> Red</a></li>
                                                    <li><a class="action-confirm" data-confirm="#change-rag-modal"
                                                           href="{{route('project.raid.rag',[
                                                    'id'=>$project_id,
                                                    'raid'=>$e->id,
                                                    'rag'=>'amber'
                                               ])}}"><i class="fa  fa-circle text-warning"> </i> Amber</a></li>
                                                    <li><a class="action-confirm" data-confirm="#change-rag-modal"
                                                           href="{{route('project.raid.rag',[
                                                    'id'=>$project_id,
                                                    'raid'=>$e->id,
                                                    'rag'=>'green'
                                               ])}}"><i class="fa  fa-circle text-success"> </i> Green</a></li>
                                                    @if(!$e->deleted_at != null)
                                                        <li role="separator" class="divider"></li>

                                                        <li><a class="form-confirm" data-confirm="#close-modal" href="{{route('project.raid.destroy',[
                                                    'id'=>$project_id,
                                                    'raid'=>$e->id
                                               ])}}">
                                                                <i class="fa  fa-check"> </i> Close</a>
                                                        </li>
                                                    @endif
                                                </ul>
                                            </div>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endif

resources/views/pages/project/partials/topnav.blade.php
<div class="btn-group btn-group-sm text-right pull-right padding-7">
    <a class="btn btn-default" href="{{route('project.index')}}">
        <i class="fa fa fa-files-o"> </i> All Projects</a>
</div>