app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', ['uses' => 'ScreenController@index', 'as' => 'screen.dashboard']);
Route::get('/error', ['uses' => 'ScreenController@error', 'as' => 'screen.error']);

Route::group(['middleware' => 'guest', 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('login', ['as' => 'login', 'uses' => 'UserController@login']);
    Route::post('login', ['as' => 'authenticate', 'uses' => 'UserController@authenticate']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'UserController@logout']);
});

Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'UserController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'UserController@create']);
        Route::post('', ['as' => 'store', 'uses' => 'UserController@store']);
        Route::get('{id}/show', ['as' => 'show', 'uses' => 'UserController@show']);
        Route::get('{id}/edit', ['as' => 'edit', 'uses' => 'UserController@edit']);
        Route::post('{id}', ['as' => 'update', 'uses' => 'UserController@update']);
        Route::get('logout', ['as' => 'logout', 'uses' => 'UserController@logout']);
        Route::get('profile', ['as' => 'editMyProfile', 'uses' => 'UserController@editMyProfile']);
        Route::post('profile', ['as' => 'updateMyProfile', 'uses' => 'UserController@updateMyProfile']);
        Route::get('password', ['as' => 'editPassword', 'uses' => 'UserController@editPassword']);
        Route::post('password', ['as' => 'updatePassword', 'uses' => 'UserController@updatePassword']);
    });
    Route::group(['prefix' => 'project', 'as' => 'project.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'ProjectController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'ProjectController@create']);
        Route::get('{id}/edit', ['as' => 'edit', 'uses' => 'ProjectController@edit']);
        Route::get('{id}/show', ['as' => 'show', 'uses' => 'ProjectController@show']);
        Route::put('{id}', ['as' => 'update', 'uses' => 'ProjectController@update']);
        Route::post('', ['as' => 'store', 'uses' => 'ProjectController@store']);
        Route::group(['prefix' => '{id}/raid', 'as' => 'raid.'], function () {
            Route::get('create/{type}', ['as' => 'create', 'uses' => 'RaidController@create']);
            Route::get('edit/{raid}', ['as' => 'edit', 'uses' => 'RaidController@edit']);
            Route::get('rag/{raid}/{rag}', ['as' => 'rag', 'uses' => 'RaidController@rag']);
            Route::get('priority/{raid}/{priority}', ['as' => 'priority', 'uses' => 'RaidController@priority']);
            Route::post('', ['as' => 'store', 'uses' => 'RaidController@store']);
            Route::put('{raid}', ['as' => 'update', 'uses' => 'RaidController@update']);
            Route::delete('{raid}', ['as' => 'destroy', 'uses' => 'RaidController@destroy']);
        });
        Route::group(['prefix' => '{id}/delay', 'as' => 'delay.'], function () {
            Route::get('create', ['as' => 'create', 'uses' => 'Project\DelayController@create']);
            Route::post('', ['as' => 'store', 'uses' => 'Project\DelayController@store']);
        });
    });
});

Route::controller('/sample', 'SampleController');

app/Models/Project.php
<?php
/**
 * Created by PhpStorm.
 * User: madam
 * Date: 10/14/2015
 * Time: 5:41 PM
 */

namespace App\Models;

use App\Models\Project\Delay;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Project extends Base
{
    use SoftDeletes;
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'projects';


    public function customer()
    {
        return $this->belongsTo(Customers::class);
    }

    public function pm()
    {
        return $this->belongsTo(User::class);
    }

    public function csm()
    {
        return $this->belongsTo(User::class);
    }

    public function delays()
    {
        $relation = $this->hasMany(Delay::class);
        return $relation->orderBy('created_at', 'DESC')->orderBy('id', 'DESC');
    }

    public function getModifiedEndDateAttribute()
    {
        $estimation = new Carbon($this->attributes['estimated_at']);
        return $estimation->addWeekdays($this->delays->sum('days'))->format(self::DATE_MASK);
    }


    public function risks()
    {
        $relation = $this->hasMany(Raid::class);
        return $relation->where('type', 'risk');
    }

    public function actions()
    {
        $relation = $this->hasMany(Raid::class);
        return $relation->where('type', 'action');
    }

    public function issues()
    {
        $relation = $this->hasMany(Raid::class);
        return $relation->where('type', 'issue');
    }

    public function dependencies()
    {
        $relation = $this->hasMany(Raid::class);
        return $relation->where('type', 'dependency');
    }


}

app/Models/Project/Delay.php
<?php

namespace App\Models\Project;

use App\Models\Project;
use App\Models\Base;
use Carbon\Carbon;

class Delay extends Base
{
    protected $table = 'project_delay';

    public function project()
    {
        return $this->belongsTo(Project::class);
    }

   
}

app/Http/Controllers/Api/V1/ProjectController.php
<?php

namespace App\Http\Controllers\Api\V1;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Project;
use Response;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = ["type_id" => "2",
            "phase_id" => "2",
            "customer_id" => "5",
            "pm_id" => "muhammet.alay@monitise.com",
            "rank_id" => "2",
            "name" => "sss",
            "code" => "ssss",
            "complete" => "0",
            "reason" => "sss",
            "started_at" => "14/10/2015",
            "estimated_at" => "23/10/2015",
            "finished_at" => "30/10/2015",
            "updated_at" => "2015-10-14 15:16:48",
            "created_at" => "2015-10-14 15:16:48"];
        $project = new Project();
        try {
            $project->insert($request->all());
            return Response::json($project);
        } catch (\Exception $e) {
            return Response::json([
                'error' => $e->getMessage(),
                'project' => $project
            ]);
        }


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $project = new Project();

        $project->type_id = $request->get('type_id');
        $project->phase_id = $request->get('phase_id');
        $project->customer_id = $request->get('customer_id');
        $project->pm_id = $request->get('pm_id');
        $project->rank_id = $request->get('rank_id');
        $project->name = $request->get('name');
        $project->code = $request->get('code');
        $project->complete = $request->get('complete');
        $project->reason = $request->get('reason');
        $project->started_at = $request->get('started_at');
        $project->estimated_at = $request->get('estimated_at');
        $project->finished_at = $request->get('finished_at');
//        dd($project);
        try {
            $project->save();
            return Response::json($project);
        } catch (\Exception $e) {
            return Response::json([
                'error' => $e->getMessage(),
                'project' => $project
            ]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Api/V2/ProjectController.php
<?php

namespace App\Http\Controllers\Api\V2;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Response;
use Ps\Repository as Ps;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $ps = new Ps();
        $ps->login();

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Project/DelayController.php
<?php

namespace App\Http\Controllers\Project;

use App\Models\Project;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Project\Delay;
use App\Http\Requests\Project\CreateDelayRequest;

class DelayController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($projecyId)
    {
        $delay = new Delay();
        $delay->project_id = $projecyId;
        $delay->dependency = old('dependency');
        $delay->category = old('category');
        $delay->reason = old('phase');
        $delay->days = old('days');

        return view('pages.project.delay.form', [
            'delay' => $delay,
            'form' => [
                'url' => route('project.delay.store', ['id' => $projecyId]),
                'method' => 'post',
                'name' => 'Delay project'
            ]
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store($projectId, CreateDelayRequest $request)
    {
        $delay = new Delay();
        $delay->project_id = $projectId;
        $delay->days = $request->days;
        $delay->dependency = $request->dependency;
        $delay->category = $request->category;
        $delay->reason = $request->reason;
        try {
            $delay->save();
            $delay->project->touch();
            return redirect()->route('project.show', [$projectId]);
        } catch (\Exception $e) {
            return redirect()->route('screen.error')->withErrors(['errors' => $e->getMessage()]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/project/show/charts.blade.php
<div class="row">
    {{--<div class="col-lg-4">--}}
    {{--@include('pages.project.show.chart.panel', ['title'=>'Completion', 'data'=>[--}}
    {{--['text'=>'Incomplete', 'value'=>100-$project->complete, 'color'=>'red'],--}}
    {{--['text'=>'Complete', 'value'=>$project->complete, 'color'=>'green']--}}
    {{--]])--}}
    {{--</div>--}}
    @if(!empty($project->chart()->risks()['counter']))
        <div class="col-lg-3">
            @include('pages.project.show.chart.panel', [
                'title'=>'Risks',
                'data'=>$project->chart()->risks(),
                'component'=>'risk',
                'container'=>'risks-panel-report',
                'counter' =>  $project->getRagIndex('risks', false)
            ])
        </div>
    @endif
    @if(!empty($project->chart()->issues()['counter']))
        <div class="col-lg-3">
            @include('pages.project.show.chart.panel', [
                'title'=>'Issues',
                'data'=>$project->chart()->issues(),
                'component'=>'issue',
                'container'=>'issues-panel-report',
                'counter' =>  $project->getRagIndex('issues', false)
             ])
        </div>
    @endif
    @if(!empty($project->chart()->dependencies()['counter']))
        <div class="col-lg-3">
            @include('pages.project.show.chart.panel', [
                'title'=>'Dependencies',
                'data'=>$project->chart()->dependencies(),
                'component'=>'dependency',
                'container'=>'dependencies-panel-report',
                'counter' =>  $project->getRagIndex('dependencies', false)
            ])
        </div>
    @endif

    @if(!empty($project->chart()->actions()['counter']))
        <div class="col-lg-3">
            @include('pages.project.show.chart.panel', [
                'title'=>'Actions',
                'data'=>$project->chart()->actions(),
                'component'=>'action',
                'container'=>'actions-panel-report',
                'counter' =>  $project->getRagIndex('actions', false)
             ])
        </div>
    @endif
    {{--<div class="col-lg-4">--}}
    {{--@include('pages.project.show.chart.panel', ['title'=>'Open Actions', 'data'=>[--}}
    {{--['text'=>'Blue', 'value'=>rand(0,100), 'color'=>'blue'],--}}
    {{--['text'=>'Green', 'value'=>rand(0,100), 'color'=>'green']--}}
    {{--]])--}}
    {{--</div>--}}

    {{--<div class="col-lg-4">--}}
    {{--@include('pages.project.show.chart.panel', ['title'=>'Open Changes', 'data'=>[--}}
    {{--['text'=>'Blue', 'value'=>rand(0,100), 'color'=>'blue'],--}}
    {{--['text'=>'Green', 'value'=>rand(0,100), 'color'=>'green']--}}
    {{--]])--}}
    {{--</div>--}}
    {{--<div class="col-lg-4">--}}
    {{--@include('pages.project.show.chart.panel', ['title'=>'Open CR', 'data'=>[--}}
    {{--['text'=>'Blue', 'value'=>rand(0,100), 'color'=>'blue'],--}}
    {{--['text'=>'Green', 'value'=>rand(0,100), 'color'=>'green']--}}
    {{--]])--}}
    {{--</div>--}}

</div>

resources/views/pages/project/show/general.blade.php
<table class="table table-responsive">
    <tbody>
    <tr>
        <td class="col-sm-6">Project No.:</td>
        <td>{{$project->code}}</td>
    </tr>
    <tr>
        <td>Phase:</td>
        <td>{{trans('component.phase.'.$project->phase)}}</td>
    </tr>
    <tr>
        <td>Start date:</td>
        <td>{{$project->date('started_at')}}</td>
    </tr>
    <tr>
        <td>End date:</td>
        <td>{{$project->date('estimated_at')}}</td>
    </tr>
    <tr>
    @if(!$project->delays->isEmpty())
        <tr>
            <td class="col-sm-6">Modified end date:</td>
            <td>
                {{$project->modifiedEndDate}}
                <a data-toggle="modal" data-target="#delays"><i class="fa fa-question-circle"> </i></a>
            </td>
        </tr>
        <tr>
            <td class="col-sm-6">Reason for modified end date:</td>
            <td>
                {{$project->delays->first()->reason}}
                <a data-toggle="modal" data-target="#delays"><i class="fa fa-question-circle"> </i></a>
            </td>
        </tr>
    @endif
    <tr>
        <td class="col-sm-6">Customer:</td>
        <td>{{$project->customer->name}}</td>
    </tr>
    <tr>
        <td class="col-sm-6">CSM:</td>
        <td> {{(null != $project->csm) ? $project->csm->name : ''}}</td>
    </tr>
    <tr>
        <td>Client contact:</td>
        <td>{{$project->client_contact}}</td>
    </tr>
    <tr>
        <td>Project Manager:</td>
        <td> {{(null != $project->pm) ? $project->pm->name : ''}}</td>
    </tr>
    <tr>
        <td>Overall project status:</td>
        <td>
            @if ($project->rag == 'red')
                <span class="text-danger">
                            <i class="fa fa-lg fa-circle"></i> {{trans('component.color.'.$project->rag)}}
                        </span>
            @elseif($project->rag == 'amber')
                <span class="text-warning">
                            <i class="fa fa-lg fa-circle"></i> {{trans('component.color.'.$project->rag)}}
                        </span>
            @else
                <span class="text-success">
                            <i class="fa fa-lg fa-circle"></i> {{trans('component.color.'.$project->rag)}}
                        </span>
            @endif
        </td>
    </tr>
    <tr>
        <td>Executive summary:
        </td>
        <td>{{$project->summary}}</td>
    </tr>
    <tr>
        <td>Actions performed during last week:
        </td>
        <td>{{$project->actions_lw}}</td>
    </tr>
    <tr>
        <td>Actions planned for next week:
        </td>
        <td>{{$project->actions_nw}}</td>
    </tr>
    <tr>
        <td>

        </td>
        <td>
            <div class="btn-group btn-group-sm pull-right">

                <div class="dropdown">
                    <a role="button" class="btn btn-default btn-sm"
                       href="{{route('project.edit', ['id'=>$project->id])}}">
                        <i class="fa fa fa-pencil"> </i> Edit</a>
                    <button class="btn btn-primary btn-sm" type="button" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false"><i class="fa fa-file"> </i> Create <span class="caret"> </span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dLabel">

                        <li><a href="{{route('project.delay.create', [
                                    'id'=>$project->id
                                ])}}"> Delay</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{{route('project.raid.create', [
                                    'id'=>$project->id,
                                    'type'=>'risk'
                                ])}}"> Risk</a></li>
                        <li><a href="{{route('project.raid.create', [
                                    'id'=>$project->id,
                                    'type'=>'issue'
                                ])}}"> Issue</a></li>

                        <li><a href="{{route('project.raid.create', [
                                    'id'=>$project->id,
                                    'type'=>'dependency'
                                ])}}"> Dependency</a></li>
                        <li><a href="{{route('project.raid.create', [
                                    'id'=>$project->id,
                                    'type'=>'action'
                                ])}}"> Action</a></li>
                    </ul>

                </div>
            </div>
        </td>
    </tr>
    </tbody>
</table>


<!-- Modal -->
<div class="modal fade" id="delays" tabindex="-1" role="dialog" aria-labelledby="delays">
    <div class="modal-dialog modal-primary" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="delays-title">Project delays</h4>
            </div>
            <div class="modal-body">
                @include('pages.project.delay.index', ['delays'=>$project->delays, 'estimation'=>$project->estimated_at])
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary " data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>