app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', ['uses' => 'ScreenController@index', 'as' => 'screen.dashboard']);
Route::get('/error', ['uses' => 'ScreenController@error', 'as' => 'screen.error']);

Route::group(['middleware' => 'guest', 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('login', ['as' => 'login', 'uses' => 'UserController@login']);
    Route::post('login', ['as' => 'authenticate', 'uses' => 'UserController@authenticate']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'UserController@logout']);
});

Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'UserController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'UserController@create']);
        Route::post('', ['as' => 'store', 'uses' => 'UserController@store']);
        Route::get('{id}/show', ['as' => 'show', 'uses' => 'UserController@show']);
        Route::get('{id}/edit', ['as' => 'edit', 'uses' => 'UserController@edit']);
        Route::post('{id}', ['as' => 'update', 'uses' => 'UserController@update']);
        Route::get('logout', ['as' => 'logout', 'uses' => 'UserController@logout']);
        Route::get('profile', ['as' => 'editMyProfile', 'uses' => 'UserController@editMyProfile']);
        Route::post('profile', ['as' => 'updateMyProfile', 'uses' => 'UserController@updateMyProfile']);
        Route::get('password', ['as' => 'editPassword', 'uses' => 'UserController@editPassword']);
        Route::post('password', ['as' => 'updatePassword', 'uses' => 'UserController@updatePassword']);
    });
    Route::group(['prefix' => 'project', 'as' => 'project.'], function () {
        Route::get('', ['as' => 'index', 'uses' => 'ProjectController@index']);
        Route::get('create', ['as' => 'create', 'uses' => 'ProjectController@create']);
        Route::get('{id}/edit', ['as' => 'edit', 'uses' => 'ProjectController@edit']);
        Route::get('{id}/show', ['as' => 'show', 'uses' => 'ProjectController@show']);
        Route::put('{id}', ['as' => 'update', 'uses' => 'ProjectController@update']);
        Route::post('', ['as' => 'store', 'uses' => 'ProjectController@store']);
        Route::group(['prefix' => '{id}/raid', 'as' => 'raid.'], function () {
            Route::get('create/{type}', ['as' => 'create', 'uses' => 'RaidController@create']);
            Route::get('edit/{raid}', ['as' => 'edit', 'uses' => 'RaidController@edit']);
            Route::get('rag/{raid}/{rag}', ['as' => 'rag', 'uses' => 'RaidController@rag']);
            Route::get('priority/{raid}/{priority}', ['as' => 'priority', 'uses' => 'RaidController@priority']);
            Route::post('', ['as' => 'store', 'uses' => 'RaidController@store']);
            Route::put('{raid}', ['as' => 'update', 'uses' => 'RaidController@update']);
            Route::delete('{raid}', ['as' => 'destroy', 'uses' => 'RaidController@destroy']);
        });
        Route::group(['prefix' => '{id}/delay', 'as' => 'delay.'], function () {
            Route::get('create', ['as' => 'create', 'uses' => 'Project\DelayController@create']);
            Route::post('', ['as' => 'store', 'uses' => 'Project\DelayController@store']);
        });
    });
});

Route::controller('/sample', 'SampleController');

resources/views/partials/menus/dev.blade.php
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-messages">
        <li>
            <a href="#">
                <div>
                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                </div>
                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                </div>
                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                </div>
                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a class="text-center" href="#">
                <strong>Read All Messages</strong>
                <i class="fa fa-angle-right"></i>
            </a>
        </li>
    </ul>
    <!-- /.dropdown-messages -->
</li>
<!-- /.dropdown -->
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-tasks fa-fw"></i> <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-tasks">
        <li>
            <a href="#">
                <div>
                    <p>
                        <strong>Task 1</strong>
                        <span class="pull-right text-muted">40% Complete</span>
                    </p>

                    <div class="progress progress-striped active">
                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40"
                             aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                            <span class="sr-only">40% Complete (success)</span>
                        </div>
                    </div>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <p>
                        <strong>Task 2</strong>
                        <span class="pull-right text-muted">20% Complete</span>
                    </p>

                    <div class="progress progress-striped active">
                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20"
                             aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                            <span class="sr-only">20% Complete</span>
                        </div>
                    </div>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <p>
                        <strong>Task 3</strong>
                        <span class="pull-right text-muted">60% Complete</span>
                    </p>

                    <div class="progress progress-striped active">
                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60"
                             aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                            <span class="sr-only">60% Complete (warning)</span>
                        </div>
                    </div>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <p>
                        <strong>Task 4</strong>
                        <span class="pull-right text-muted">80% Complete</span>
                    </p>

                    <div class="progress progress-striped active">
                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80"
                             aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                            <span class="sr-only">80% Complete (danger)</span>
                        </div>
                    </div>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a class="text-center" href="#">
                <strong>See All Tasks</strong>
                <i class="fa fa-angle-right"></i>
            </a>
        </li>
    </ul>
    <!-- /.dropdown-tasks -->
</li>
<!-- /.dropdown -->
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-alerts">
        <li>
            <a href="#">
                <div>
                    <i class="fa fa-comment fa-fw"></i> New Comment
                    <span class="pull-right text-muted small">4 minutes ago</span>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                    <span class="pull-right text-muted small">12 minutes ago</span>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <i class="fa fa-envelope fa-fw"></i> Message Sent
                    <span class="pull-right text-muted small">4 minutes ago</span>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <i class="fa fa-tasks fa-fw"></i> New Task
                    <span class="pull-right text-muted small">4 minutes ago</span>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a href="#">
                <div>
                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                    <span class="pull-right text-muted small">4 minutes ago</span>
                </div>
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <a class="text-center" href="#">
                <strong>See All Alerts</strong>
                <i class="fa fa-angle-right"></i>
            </a>
        </li>
    </ul>
    <!-- /.dropdown-alerts -->
</li>


<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-question fa-fw"></i> <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-user">
        <li><a href="/sample/dashboard"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a></li>
        <li class="divider"></li>

        <li><a href="/sample/morris"><i class="fa fa-pie-chart fa-fw"></i> Morris</a></li>
        <li><a href="/sample/flot"><i class="fa fa-pie-chart fa-fw"></i> Flot</a></li>
        <li class="divider"></li>

        <li><a href="/sample/tables"><i class="fa fa-table fa-fw"></i> Tables</a></li>
        <li class="divider"></li>

        <li><a href="/sample/forms"><i class="fa fa-edit fa-fw"></i> Forms</a></li>
        <li class="divider"></li>

        <li><a href="/sample/panels-wells"><i class="fa fa-windows fa-fw"></i> Panels / Wells</a></li>
        <li><a href="/sample/buttons"><i class="fa fa-keyboard-o fa-fw"></i> Buttons</a></li>
        <li><a href="/sample/notifications"><i class="fa fa-bell fa-fw"></i> Notifications</a></li>
        <li><a href="/sample/typography"><i class="fa fa-font fa-fw"></i> Typography</a></li>
        <li><a href="/sample/icons"><i class="fa fa-facebook fa-fw"></i> Icons</a></li>
        <li><a href="/sample/grid"><i class="fa fa-table fa-fw"></i> Grid</a></li>
        <li class="divider"></li>

        <li><a href="/sample/blank"><i class="fa fa-square-o fa-fw"></i> Blank</a></li>
        <li><a href="/sample/login"><i class="fa fa-user fa-fw"></i> Login</a></li>
    </ul>
    <!-- /.dropdown-user -->
</li>

resources/views/partials/menus/top.blade.php
<!-- /.navbar-header -->

<ul class="nav navbar-top-links navbar-right" style="margin-right: 0px;">
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-files-o fa-fw"></i> Projects <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-projects">
            <li>
                <a href="{{route('project.index')}}">
                    <i class="fa fa-files-o fa-fw"></i> All
                </a>
            </li>
            <li>
                <a href="{{route('project.create')}}">
                    <i class="fa fa fa-plus-square"> </i> Add</a>
            </li>
        </ul>
    </li>
    @if(config('theme.devmenu', false))
        @include('partials.menus.dev')
    @endif
    @can('manage-users')
    <li class="">
        <a href="{{route('user.index')}}">
            <i class="fa fa-users fa-fw"></i> Manage users
        </a>

        <!-- /.dropdown-user -->
    </li>
    @endcan
            <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="">
            <i class="fa fa-user fa-fw"></i> User <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li><a href="{{route('user.editMyProfile')}}"><i class="fa fa-user fa-fw"></i> Profile</a></li>
            <li><a href="{{route('user.editPassword')}}"><i class="fa fa-lock fa-fw"></i> Change password</a></li>
            <li class="divider"></li>
            <li><a href="{{route('user.logout')}}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
            </li>
        </ul>
        <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->

    <li class="">
        <a href="#">
            <i class="fa fa-arrow-circle-o-up fa-lg"></i>
        </a>

        <!-- /.dropdown-user -->
    </li>
</ul>
<!-- /.navbar-top-links -->